export const SET_PRODUCT = "SET_PRODUCT";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const PRODUCT_COUNT = "PRODUCT_COUNT";
export const CLEAR_CART = "CLEAR_CART";

